### PR TITLE
update version of slugbuilder and slugrunner

### PR DESCRIPTION
**Pull request by drgarcia1986**
This change is [Reviewable](https://reviewable.io/reviews/luizalabs/teresa-api/154)

### CODE REVIEW

**Comment by alexguerra-luizalabs** [comment]
It would be nice to back up these slugs at registry.appsluiza.com.br
LGTM :+1:

**Comment by drgarcia1986** [comment]
@arnaldopereira Can you help us with our docker registry?

**Comment by drgarcia1986** [comment]
Works like a charm 🎉

**Comment by drgarcia1986** [comment]
I'll update changelog

**Comment by drgarcia1986** [comment]
Done

**Pull request merged**
