### PR TITLE
some improves in README

### PR DESCRIPTION
**Pull request by drgarcia1986**
- add tips to deploy python, nodejs and golang application
- explain about procfile
- explain about $PORT (env var)
- doc healthcheck based on teresa.yaml
- doc rolling update deployment based on teresa.yaml

---
This change is [Reviewable](https://reviewable.io/reviews/luizalabs/teresa-api/155)

### CODE REVIEW

**Comment by alexguerra-luizalabs** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[README.md, line 95 at r1](https://reviewable.io:443/reviews/luizalabs/teresa-api/155#-KcZWfhBvyIKzJjrVsNp:-KcZWfhBvyIKzJjrVsNq:b-twqtcg) ([raw file](https://github.com/luizalabs/teresa-api/blob/35c0d66c8a3dac686d7e999e408e2a73b23c2e66/README.md#L95)):*
> ```Markdown
> Steps to setup a new cluster and deploy a new application, assuming you already have the API running:
> 
>     $ teresa config set-cluster mycluster --server <k8s-endpoint>
> ```

Writing k8s-endpoint may suggest the k8s api endpoint, but we need here the teresa service endpoint

---

*[README.md, line 117 at r1](https://reviewable.io:443/reviews/luizalabs/teresa-api/155#-KcZUy7VKTfpGhIMApsE:-KcZUy7VKTfpGhIMApsF:bvxdau9) ([raw file](https://github.com/luizalabs/teresa-api/blob/35c0d66c8a3dac686d7e999e408e2a73b23c2e66/README.md#L117)):*
> ```Markdown
> ## Deploy
> 
> Some informations to up and run your application on Kubernetes with Teresa.
> ```

I think information has no plural 

---

*[README.md, line 199 at r1](https://reviewable.io:443/reviews/luizalabs/teresa-api/155#-KcZWQWikSNH37pTmEs4:-KcZWQWikSNH37pTmEs5:b-key6gb) ([raw file](https://github.com/luizalabs/teresa-api/blob/35c0d66c8a3dac686d7e999e408e2a73b23c2e66/README.md#L199)):*
> ```Markdown
> the `Readiness` and the `Liveness`.
> 
> - **Readiness**: Based on the time of "boot" of application, the Kubernetes uses this configuration to know when container is ready to start acception traffic.
> ```

"to start acception traffic" sounds strange

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/luizalabs/teresa-api/155)*

**Comment by alexguerra-luizalabs** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/luizalabs/teresa-api/155)*

**Comment by drgarcia1986** [comment]
*[README.md, line 95 at r1](https://reviewable.io:443/reviews/luizalabs/teresa-api/155#-KcZWfhBvyIKzJjrVsNp:-KcZj0p5Xxmtr5_0YzW1:bh764id) ([raw file](https://github.com/luizalabs/teresa-api/blob/35c0d66c8a3dac686d7e999e408e2a73b23c2e66/README.md#L95)):*
<details><summary><i>Previously, alexguerra-luizalabs (Alex Guerra) wrote…</i></summary><blockquote>

Writing k8s-endpoint may suggest the k8s api endpoint, but we need here the teresa service endpoint
</blockquote></details>

yeah, you're right! I'll fix

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/luizalabs/teresa-api/155)*

**Comment by drgarcia1986** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[README.md, line 117 at r1](https://reviewable.io:443/reviews/luizalabs/teresa-api/155#-KcZUy7VKTfpGhIMApsE:-KcZie3evRhl4u4fWOZl:b-8fx2u7) ([raw file](https://github.com/luizalabs/teresa-api/blob/35c0d66c8a3dac686d7e999e408e2a73b23c2e66/README.md#L117)):*
<details><summary><i>Previously, alexguerra-luizalabs (Alex Guerra) wrote…</i></summary><blockquote>

I think information has no plural 
</blockquote></details>

:+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/luizalabs/teresa-api/155)*

**Comment by drgarcia1986** [comment]
*[README.md, line 95 at r1](https://reviewable.io:443/reviews/luizalabs/teresa-api/155#-KcZWfhBvyIKzJjrVsNp:-KcZjTB77BJ2dUiQVH7F:b-j2fub9) ([raw file](https://github.com/luizalabs/teresa-api/blob/35c0d66c8a3dac686d7e999e408e2a73b23c2e66/README.md#L95)):*
<details><summary><i>Previously, drgarcia1986 (Diego Garcia) wrote…</i></summary><blockquote>

yeah, you're right! I'll fix
</blockquote></details>

what about `<teresa-endpoint>` ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/luizalabs/teresa-api/155)*

**Comment by drgarcia1986** [comment]
*[README.md, line 199 at r1](https://reviewable.io:443/reviews/luizalabs/teresa-api/155#-KcZWQWikSNH37pTmEs4:-KcZk4JYqpgQO58soJV3:b-lcltvb) ([raw file](https://github.com/luizalabs/teresa-api/blob/35c0d66c8a3dac686d7e999e408e2a73b23c2e66/README.md#L199)):*
<details><summary><i>Previously, alexguerra-luizalabs (Alex Guerra) wrote…</i></summary><blockquote>

"to start acception traffic" sounds strange
</blockquote></details>

What about `to start accepting traffic`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/luizalabs/teresa-api/155)*

**Comment by alexguerra-luizalabs** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/luizalabs/teresa-api/155#-:-Kcbpr2I2PHRG82aKHFL:bnfp4nl)*

**Comment by lucianokadoya-luizalabs** [comment]
:+1:

**Pull request merged**
